//! Filesystem contract for the daemon and clients. Code-as-spec: every
//! path and file format shared between components is defined here, so
//! the pieces can be built independently.
//!
//! File formats:
//! - `hosts.json` (client, read by muxd's broker AND by Mux.app):
//!   `{ "spark": { "addr": "100.64.0.7:4433" } }` - host alias to
//!   QUIC endpoint. JSON, not TOML, so Swift Codable parses it too.
//! - `known_hosts` (client): one line per host, `<alias> sha256:<b64>`
//!   where the hash is SHA-256 of the server certificate's SPKI
//!   (trust-on-first-use, like ssh).
//! - client `token`: this client's own bearer token, 32 random bytes as
//!   hex, generated 0600 on first use. Presented to every host; the
//!   secret never leaves the machine, only `sha256:<64 hex>` of it does
//!   (`muxd client-digest`), which the host enrolls in its
//!   `--authorized-tokens` file.
//! - `tokens/<alias>` (client): a per-host override of that token, for a
//!   host that hands out its own instead of enrolling ours. 0600.
//! - daemon `cert.pem` / `key.pem`: self-signed, generated by rcgen on
//!   first QUIC listen; the SPKI hash is logged for out-of-band pinning.
//! - daemon `token`: random bearer token generated 0600 on first QUIC
//!   listen; always admitted by that daemon.
//! - daemon authorized-tokens file (path given by `--authorized-tokens`,
//!   not under `$HOME`): one `sha256:<64 hex>` digest per line, `#`
//!   comments and blank lines ignored. Digests are not secrets, so the
//!   file can be world-readable and live in a nix store.

use std::path::PathBuf;

fn home() -> PathBuf {
    // Panicking here is worse than degrading: this is called lazily from
    // request handlers (broker init), where a panic poisons a OnceLock
    // and turns every later request into a repeat panic. home_dir reads
    // HOME and falls back to the passwd entry.
    #[allow(deprecated)] // un-deprecated in newer std; harmless here
    std::env::home_dir().unwrap_or_else(|| PathBuf::from("/"))
}

/// Client host registry: `~/.config/mux/hosts.json`.
#[must_use]
pub fn hosts_config() -> PathBuf {
    home().join(".config/mux/hosts.json")
}

/// Client-side state: `~/.local/state/mux/`.
#[must_use]
pub fn client_state_dir() -> PathBuf {
    home().join(".local/state/mux")
}

/// TOFU pin store: `~/.local/state/mux/known_hosts`.
#[must_use]
pub fn known_hosts() -> PathBuf {
    client_state_dir().join("known_hosts")
}

/// This client's own bearer token: `~/.local/state/mux/token`. One
/// identity for every host, so enrolling a new host is a digest paste
/// rather than a secret copy.
#[must_use]
pub fn client_token() -> PathBuf {
    client_state_dir().join("token")
}

/// Per-host override of [`client_token`]:
/// `~/.local/state/mux/tokens/<alias>`.
#[must_use]
pub fn host_token(alias: &str) -> PathBuf {
    client_state_dir().join("tokens").join(alias)
}

/// Daemon-side state: `~/.local/state/muxd/`.
#[must_use]
pub fn daemon_state_dir() -> PathBuf {
    home().join(".local/state/muxd")
}

#[must_use]
pub fn daemon_cert() -> PathBuf {
    daemon_state_dir().join("cert.pem")
}

#[must_use]
pub fn daemon_key() -> PathBuf {
    daemon_state_dir().join("key.pem")
}

#[must_use]
pub fn daemon_token() -> PathBuf {
    daemon_state_dir().join("token")
}

/// Running daemon's pidfile: `~/.local/state/muxd/muxd.pid`, one decimal
/// pid and a newline. Written at startup; the successor reads it to know
/// which process to ask for a live-fd handoff (see `migrate.rs`). Derived
/// from `HOME` on purpose, so a test daemon with its own `HOME` never
/// signals the user's.
#[must_use]
pub fn daemon_pid() -> PathBuf {
    daemon_state_dir().join("muxd.pid")
}
