//! Filesystem contract for the daemon and clients. Code-as-spec: every
//! path and file format shared between components is defined here, so
//! the pieces can be built independently.
//!
//! File formats:
//! - `hosts.json` (client, read by muxd's broker AND by Mux.app):
//!   `{ "spark": { "addr": "100.64.0.7:4433" } }` - host alias to
//!   QUIC endpoint. JSON, not TOML, so Swift Codable parses it too.
//! - `known_hosts` (client): one line per host, `<alias> sha256:<b64>`
//!   where the hash is SHA-256 of the server certificate's SPKI
//!   (trust-on-first-use, like ssh).
//! - `tokens/<alias>` (client): the bearer token for that host, copied
//!   once from the server's `token` file. 0600.
//! - daemon `cert.pem` / `key.pem`: self-signed, generated by rcgen on
//!   first QUIC listen; the SPKI hash is logged for out-of-band pinning.
//! - daemon `token`: random bearer token generated 0600 on first QUIC
//!   listen; required on every QUIC-originated request.

use std::path::PathBuf;

fn home() -> PathBuf {
    PathBuf::from(std::env::var_os("HOME").expect("HOME is not set"))
}

/// Client host registry: `~/.config/mux/hosts.json`.
#[must_use]
pub fn hosts_config() -> PathBuf {
    home().join(".config/mux/hosts.json")
}

/// Client-side state: `~/.local/state/mux/`.
#[must_use]
pub fn client_state_dir() -> PathBuf {
    home().join(".local/state/mux")
}

/// TOFU pin store: `~/.local/state/mux/known_hosts`.
#[must_use]
pub fn known_hosts() -> PathBuf {
    client_state_dir().join("known_hosts")
}

/// Bearer token for a host: `~/.local/state/mux/tokens/<alias>`.
#[must_use]
pub fn host_token(alias: &str) -> PathBuf {
    client_state_dir().join("tokens").join(alias)
}

/// Daemon-side state: `~/.local/state/muxd/`.
#[must_use]
pub fn daemon_state_dir() -> PathBuf {
    home().join(".local/state/muxd")
}

#[must_use]
pub fn daemon_cert() -> PathBuf {
    daemon_state_dir().join("cert.pem")
}

#[must_use]
pub fn daemon_key() -> PathBuf {
    daemon_state_dir().join("key.pem")
}

#[must_use]
pub fn daemon_token() -> PathBuf {
    daemon_state_dir().join("token")
}

/// Running daemon's pidfile: `~/.local/state/muxd/muxd.pid`, one decimal
/// pid and a newline. Written at startup; the successor reads it to know
/// which process to ask for a live-fd handoff (see `migrate.rs`). Derived
/// from `HOME` on purpose, so a test daemon with its own `HOME` never
/// signals the user's.
#[must_use]
pub fn daemon_pid() -> PathBuf {
    daemon_state_dir().join("muxd.pid")
}
