//! Every filesystem location the daemon and its clients share, defined
//! once. Code-as-spec: a component can be built against this module
//! alone.
//!
//! File formats:
//! - `hosts.json` (client, read by muxd's broker AND by Mux.app):
//!   `{ "spark": { "addr": "100.64.0.7:4433" } }` - host alias to
//!   QUIC endpoint. JSON, not TOML, so Swift Codable parses it too.
//! - `known_hosts` (client): one line per host, `<alias> sha256:<b64>`
//!   where the hash is SHA-256 of the server certificate's DER
//!   (trust-on-first-use, like ssh).
//! - client `token`: this client's own bearer token, 32 random bytes as
//!   hex, generated 0600 on first use. Presented to every host; the
//!   secret never leaves the machine, only `sha256:<64 hex>` of it does
//!   (`muxd client-digest`), which the host enrolls in its
//!   `--authorized-tokens` file.
//! - `tokens/<alias>` (client): a per-host override of that token, for a
//!   host that hands out its own instead of enrolling ours. 0600.
//! - daemon `cert.pem` / `key.pem`: self-signed, generated by rcgen on
//!   first QUIC listen, and regenerated together if either is missing.
//! - daemon `token`: random bearer token generated 0600 on first QUIC
//!   listen; always admitted by that daemon.
//! - daemon authorized-tokens file (path given by `--authorized-tokens`,
//!   not under `$HOME`): one `sha256:<64 hex>` digest per line, `#`
//!   comments and blank lines ignored. Digests are not secrets, so the
//!   file can be world-readable and live in a nix store.

use std::path::PathBuf;

use mux_proto::peer;

fn home() -> PathBuf {
    // Panicking here is worse than degrading: this is called lazily from
    // request handlers (broker init), where a panic poisons a OnceLock
    // and turns every later request into a repeat panic. home_dir reads
    // HOME and falls back to the passwd entry.
    #[allow(deprecated)] // un-deprecated in newer std; harmless here
    std::env::home_dir().unwrap_or_else(|| PathBuf::from("/"))
}

/// Client host registry: `~/.config/mux/hosts.json`.
pub fn hosts_config() -> PathBuf {
    home().join(".config/mux/hosts.json")
}

/// Client-side state: `~/.local/state/mux/`.
pub fn client_state_dir() -> PathBuf {
    home().join(".local/state/mux")
}

/// TOFU pin store: `~/.local/state/mux/known_hosts`.
pub fn known_hosts() -> PathBuf {
    client_state_dir().join("known_hosts")
}

/// This client's own bearer token: `~/.local/state/mux/token`. One
/// identity for every host, so enrolling a new host is a digest paste
/// rather than a secret copy.
pub fn client_token() -> PathBuf {
    client_state_dir().join("token")
}

/// Per-host overrides of [`client_token`]: `~/.local/state/mux/tokens/`.
pub fn token_dir() -> PathBuf {
    client_state_dir().join("tokens")
}

/// The override for one host: `~/.local/state/mux/tokens/<alias>`.
pub fn host_token(alias: &str) -> PathBuf {
    token_dir().join(alias)
}

/// Daemon-side state: `~/.local/state/muxd/`.
pub fn daemon_state_dir() -> PathBuf {
    home().join(".local/state/muxd")
}

pub fn daemon_cert() -> PathBuf {
    daemon_state_dir().join("cert.pem")
}

pub fn daemon_key() -> PathBuf {
    daemon_state_dir().join("key.pem")
}

pub fn daemon_token() -> PathBuf {
    daemon_state_dir().join("token")
}

/// Daemon log: `~/.local/state/muxd/muxd.log`. The daemon is spawned
/// detached with stderr on /dev/null, so without a file the whole pty
/// lifecycle (created/attached/killed/exited) is unobservable - and a
/// session that vanished cannot be diagnosed after the fact.
pub fn daemon_log() -> PathBuf {
    daemon_state_dir().join("muxd.log")
}

/// The daemon's control socket. [`peer::SOCKET_ENV`] overrides the
/// per-uid default for the daemon and for every client that reads it, so
/// a test daemon and its clients cannot end up on different sockets.
pub fn control_socket() -> PathBuf {
    std::env::var_os(peer::SOCKET_ENV).map_or_else(
        || peer::socket_path(nix::unistd::getuid().as_raw()),
        PathBuf::from,
    )
}

/// Self-upgrade rendezvous socket, a short /tmp path (`sun_path` is 104
/// bytes on darwin). `MUXD_MIGRATE_SOCKET` overrides the per-uid default
/// so a test daemon can never steal the user's ptys.
pub fn migrate_socket() -> PathBuf {
    std::env::var_os("MUXD_MIGRATE_SOCKET").map_or_else(
        || default_migrate_socket(nix::unistd::getuid().as_raw()),
        PathBuf::from,
    )
}

/// The per-uid [`migrate_socket`] before any override.
pub fn default_migrate_socket(uid: u32) -> PathBuf {
    PathBuf::from(format!("/tmp/muxd-{uid}-migrate.sock"))
}
